server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: bookmark-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/bookmark_managerdevdb
    username: postgres
    password: postgresad#123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: bookmark_manager
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          temp:
            use_jdbc_metada_defaults: false